[package]
name = "component-init"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
async-trait = "0.1.83"
futures = "0.3.31"
wasm-encoder = { version = "0.227.0", features = ["wasmparser"] }
wasmparser = "0.227.0"
