[package]
name = "component-init-cli"
version.workspace = true
edition.workspace = true

[[bin]]
name = "component-init"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
component-init-wasmtime.workspace = true
tokio.workspace = true
